sudo: false
language: ruby
cache: bundler
rvm:
- 2.6.6

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "hs9880@gmail.com"
  - git config --global user.name "Hyunsu Joo"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "X0pHdXjIRMXlvOaLlU84meaINy/fvWfjopoxSgQGZUlnkb67ffQvYw2n/WoxcDXSk1pbpdR1W4s523gl1fLeqG4kFsH4KGn3tcyGnCpcBGh/YEWKNjK9930NUJwsvAVoJhlBIyLE8O3RQt6JfUwgHpFnqPOH7eF3GVpjAxLMAouVlJEO62jlhzG1mUMwMbIdnfhnxgMbgpKST/NJyZUFW2qlwBUO55/kEtBBxuy1fyQ/SU1uGr1K5eYDOdyCcf7+iEDggzx8D+NCwDizgcULGWzapL6MgP5aoj17EVuXlX4KBOlk6eToEw3Lya2678TXhNsB9/FInnNTzlGHOVPAn7nJkyhdNZ65ACoXJaNuzpCk8Xx8lhJkIzElERPhj//q/dYhYRimART6H+WbwHVIq9sl/+zy2VO9z6mBbk7DyNALw7Ujem0D+p1azqPIm+Ri5pKMNyTC1S0lmCPKKe0vAHM7vKITRDGbeOjc+ufyGU6GWCJnVN/jQ5+NCWvgAZbACTbqiuPtE05rRtQ3STEeJK0HwUCB44YyFNZJ2vj7XKaNIv3isOM7xCWqR8ddHZZgwdDBheyi4yfqyDQSi3Z0AQUdPfONQ8lWeiLa8D3jujDic33XiwRfhfbV9zmFZwd8kJhuM0cnRRtQmgsK6nNWPIR6Vh6MXWweaOQJ4J5d4o="
branches:
  only:
    - master

    # deploy:
    #     provider : pages
    #     skip-cleanup: true 
    #     github-token : $GITHUB_TOKEN
    #         on:
    #             branch: master
    exclude:
    - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - node_modules
  - assets/css
  - assets/images
  - _posts/angular
  - _posts/et-cetera
  - _posts/python
  - _posts/typescript
#  - _posts/jekyll
  - _posts/iot
  - _posts/r
  - _posts/economy